# Generated by Django 3.0.5 on 2020-04-06 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(default=' ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Halls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hall_Name', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Hall_Description', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Hall_Guest_Capacity', models.IntegerField(blank=True, null=True)),
                ('Hall_Location', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Indoor', max_length=50)),
                ('Slot', models.CharField(blank=True, default='4 hours', max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.City')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Date', models.DateTimeField(blank=True, null=True)),
                ('Slot', models.CharField(choices=[('8.00 - 12.00', '8.00 - 12.00'), ('12.00 - 4.00', '12.00 - 4.00'), ('4.00 - 8.00', '4.00 - 8.00'), ('8.00', '12.00')], max_length=50)),
                ('Team_Size', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Status', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.City')),
                ('Hall_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.Event_Halls')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trans_Amount', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Trans_Time_Date', models.DateTimeField(blank=True, null=True)),
                ('Trans_Type', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('Transaction_Token', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.City')),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.Reservation')),
                ('Hall_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.Event_Halls')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Hall_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability_Start_Time', models.DateTimeField(blank=True, null=True)),
                ('Availability_End_time', models.DateTimeField(blank=True, null=True)),
                ('City_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.City')),
                ('Hall_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ehbapp.Event_Halls')),
            ],
        ),
    ]
