# Generated by Django 3.0.5 on 2020-04-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehbapp', '0002_reservation_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_halls',
            name='Hall_Location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
